dist: trusty
sudo: required
addons:
  chrome: stable
before_install:
  - # Install ChromeDriver for Selenium (IMPORTANT: this version should correspond to the version in apify-actor-docker)
  - sudo curl -sS http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip > /tmp/chromedriver.zip
  - sudo unzip /tmp/chromedriver.zip -d /tmp
  - sudo rm /tmp/chromedriver.zip
  - sudo mv /tmp/chromedriver /usr/bin/
  - # Print versions to help debugging
  - google-chrome --version
  - chromedriver --version
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
script:
  - npm run lint
  - npm test
