dist: trusty
sudo: required
addons:
  chrome: beta
before_install:
  - # Install ChromeDriver for Selenium
  - sudo curl -sS http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip > /tmp/chromedriver.zip
  - sudo unzip /tmp/chromedriver.zip -d /tmp
  - sudo rm /tmp/chromedriver.zip
  - sudo mv /tmp/chromedriver /usr/bin/
  - # Travis' VM has preinstalled google-chrome stable, which has no headless mode!
  - sudo mv -f /usr/bin/google-chrome-beta /usr/bin/google-chrome | tee
  - # Print versions to help debugging
  - google-chrome --version
  - chromedriver --version
language: node_js
node_js:
  - "8"
  - "7"
  - "6"
script:
  - npm run lint
  - npm test
