dist: trusty
sudo: required
addons:
  chrome: beta
before_install:
  - sudo curl -sS http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip > /tmp/chromedriver.zip
  - sudo unzip /tmp/chromedriver.zip -d /tmp
  - sudo rm /tmp/chromedriver.zip
  - sudo mv /tmp/chromedriver /bin
  - google-chrome --version
  - which google-chrome | tee
  - which google-chrome-beta | tee
  - google-chrome --headless --disable-gpu --screenshot https://www.chromestatus.com/
language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
script:
  - npm run lint
  - npm test
